ALTER TABLE `rika`.`led_advertisements` CHANGE COLUMN `text` `line1` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
 ADD COLUMN `line2` VARCHAR(255) NOT NULL AFTER `line1`,
 ADD COLUMN `line3` VARCHAR(255) NOT NULL AFTER `line2`,
 ADD COLUMN `line4` VARCHAR(255) NOT NULL AFTER `line3`;
